CXX = g++
#CXXFLAGS= -g 
CXXFLAGS= -O6

gen1 : gen1.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

gen2 : gen2.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

gen3 : gen3.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

gen4 : gen4.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

all : gen1 gen2 gen3 gen4
